# Pandas

Pandas es una biblioteca de programación en Python que ofrece estructuras de datos y herramientas de manipulación rápidas y flexibles. Está diseñada para facilitar el trabajo con datos "relacionales" o "etiquetados" de forma sencilla e intuitiva.

Pandas es ideal para distintos tipos de datos, desde matrices simples de números hasta series temporales y datos tabulares heterogéneos. La biblioteca proporciona dos estructuras principales: Series y DataFrames.

**¿Por qué es importante para la ciencia de datos?**

La ciencia de datos implica trabajar intensamente con los datos: limpiarlos, transformarlos, analizarlos y visualizarlos.

Por eso, pandas es una pieza clave en el ecosistema de ciencia de datos en Python. Permite importar datos desde múltiples fuentes, realizar una gran variedad de operaciones de manipulación de datos y, además, es compatible con otras bibliotecas de análisis y visualización.

https://pandas.pydata.org/

# En caso de que la librería no esté instalada, puedes hacerlo con **pip**

In [31]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Para utilizar Pandas, primero debemos importar la biblioteca. La convención habitual es importarla con el alias `pd`.

In [32]:
import pandas as pd
import numpy as np

In [33]:
from google.colab import drive
drive.mount('/content/drive')

ruta = '/content/drive/MyDrive/CURSO_MACHINE_LEARNING/CSV/datos.csv'
df = pd.read_csv(ruta)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
df

   id   nombre  edad  ingresos  compra
0   1    Laura    34      2100       1
1   2    Pedro    45      1800       0
2   3      Ana    29      3200       1
3   4    David    53      1500       0
4   5    Marta    26      2700       1
5   6    Jorge    38      2000       0
6   7     Sara    41      2500       1
7   8   Manuel    30      1900       0
8   9    Elena    22      2300       1
9  10  Ricardo    60      1700       0

In [35]:
df.head(5)  # Muestra las primeras 5 filas del DataFrame

   id nombre  edad  ingresos  compra
0   1  Laura    34      2100       1
1   2  Pedro    45      1800       0
2   3    Ana    29      3200       1
3   4  David    53      1500       0
4   5  Marta    26      2700       1

In [36]:
# Ver los tipos de datos en el DataFrame
df.dtypes

id           int64
nombre      object
edad         int64
ingresos     int64
compra       int64
dtype: object

In [37]:
# Información general del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10 non-null     int64
 1   nombre    10 non-null     object
 2   edad      10 non-null     int64
 3   ingresos  10 non-null     int64
 4   compra    10 non-null     int64
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes

In [38]:
# Pandas, internamente, define cada columna como un vector de Numpy
# Acceso a un campo
df['nombre']

0      Laura
1      Pedro
2        Ana
3      David
4      Marta
5      Jorge
6       Sara
7     Manuel
8      Elena
9    Ricardo
Name: nombre, dtype: object

In [39]:
# Seleccionar más de un campo
df[['nombre', 'edad']]

    nombre  edad
0    Laura    34
1    Pedro    45
2      Ana    29
3    David    53
4    Marta    26
5    Jorge    38
6     Sara    41
7   Manuel    30
8    Elena    22
9  Ricardo    60

In [40]:
# Seleccionar solo un elemento de un campo
df['nombre'][3]

'David'

In [41]:
# Seleccionar un rango de elementos indicando el índice final, pero incluyendo todos los campos del DataFrame. El índice 2 queda excluido.
df[:2]

   id nombre  edad  ingresos  compra
0   1  Laura    34      2100       1
1   2  Pedro    45      1800       0

In [42]:
# Seleccionar desde el elemento con índice 2 hasta el final
df[2:]

   id   nombre  edad  ingresos  compra
2   3      Ana    29      3200       1
3   4    David    53      1500       0
4   5    Marta    26      2700       1
5   6    Jorge    38      2000       0
6   7     Sara    41      2500       1
7   8   Manuel    30      1900       0
8   9    Elena    22      2300       1
9  10  Ricardo    60      1700       0

In [43]:
# Seleccionar un elemento desde el índice 2 hasta el 3, excluyendo el 3
df[2:3]

   id nombre  edad  ingresos  compra
2   3    Ana    29      3200       1

In [44]:
# Aplicar filtros al DataFrame para ver campos que cumplen una condición
df['ingresos'] > 2000

0     True
1    False
2     True
3    False
4     True
5    False
6     True
7    False
8     True
9    False
Name: ingresos, dtype: bool

In [45]:
# Creación de otro DataFrame con solo los elementos que cumplen el filtro
df2 = df[df['ingresos'] > 2000]
df2

   id nombre  edad  ingresos  compra
0   1  Laura    34      2100       1
2   3    Ana    29      3200       1
4   5  Marta    26      2700       1
6   7   Sara    41      2500       1
8   9  Elena    22      2300       1

In [46]:
# Creación de una nueva columna en un DataFrame con edad * ingresos
df2['prueba'] = df2['edad'] * df2['ingresos']
df2

/tmp/ipython-input-46-3855212091.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['prueba'] = df2['edad'] * df2['ingresos']

   id nombre  edad  ingresos  compra  prueba
0   1  Laura    34      2100       1   71400
2   3    Ana    29      3200       1   92800
4   5  Marta    26      2700       1   70200
6   7   Sara    41      2500       1  102500
8   9  Elena    22      2300       1   50600

In [47]:
# Eliminar una columna de un DataFrame, axis=1 indica que es una columna
df2 = df2.drop('prueba', axis=1)
df2

   id nombre  edad  ingresos  compra
0   1  Laura    34      2100       1
2   3    Ana    29      3200       1
4   5  Marta    26      2700       1
6   7   Sara    41      2500       1
8   9  Elena    22      2300       1

In [48]:
# Eliminar una fila
df2 = df2.drop(index=[2])
df2

   id nombre  edad  ingresos  compra
0   1  Laura    34      2100       1
4   5  Marta    26      2700       1
6   7   Sara    41      2500       1
8   9  Elena    22      2300       1