In [20]:
# ================================================================
# 1. Configuración inicial
# ================================================================
import pandas as pd
import numpy as np

# ================================================================
# 2. Creación del DataFrame de ejemplo
#    - rating: variable ordinal (1-5) con un valor nulo
#    - price : numérica continua con un valor nulo
#    - category: categórica con valores 0,1,2 y un nulo
#    - brand: texto con errores ortográficos para unificar
# ================================================================
data = {
    "rating":   [1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
                 1, 2, np.nan, 4, 5, 1, 2, 3, 4, 5],
    "price":    [10.5, 12.0, 9.99, 8.5, np.nan, 11.25, 10.0, 13.5, 9.0, 10.5,
                 10.5, 12.0, 9.99, 8.5, 7.75, 11.25, 10.0, 13.5, 9.0, 10.5],
    "category": [0, 1, 2, 0, 1, 2, 0, 1, 2, np.nan,
                 0, 1, 2, 0, 1, 2, 0, 1, 2, 0],
    "brand":    ["Sony", "Samsng", "LG", "Apple", "Sony", "Samsung", "LG", "Aple", "Sony", "LG",
                 "Sony", "Samsng", "LG", "Apple", "Sony", "Samsung", "LG", "Aple", "Sony", "LG"]
}

df = pd.DataFrame(data)
print("=== DataFrame original  ===")
df

=== DataFrame original  ===

    rating  price  category    brand
0      1.0  10.50       0.0     Sony
1      2.0  12.00       1.0   Samsng
2      3.0   9.99       2.0       LG
3      4.0   8.50       0.0    Apple
4      5.0    NaN       1.0     Sony
5      1.0  11.25       2.0  Samsung
6      2.0  10.00       0.0       LG
7      3.0  13.50       1.0     Aple
8      4.0   9.00       2.0     Sony
9      5.0  10.50       NaN       LG
10     1.0  10.50       0.0     Sony
11     2.0  12.00       1.0   Samsng
12     NaN   9.99       2.0       LG
13     4.0   8.50       0.0    Apple
14     5.0   7.75       1.0     Sony
15     1.0  11.25       2.0  Samsung
16     2.0  10.00       0.0       LG
17     3.0  13.50       1.0     Aple
18     4.0   9.00       2.0     Sony
19     5.0  10.50       0.0       LG

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    19 non-null     float64
 1   price     19 non-null     float64
 2   category  19 non-null     float64
 3   brand     20 non-null     object
dtypes: float64(3), object(1)
memory usage: 772.0+ bytes

In [22]:
#NULOS

# rating → mediana (valor central de la serie ordenada)
df["rating"] = df["rating"].fillna(round(df["rating"].median()))

# price → media (promedio aritmético de los valores)
df["price"] = df["price"].fillna(df["price"].mean())

# category → moda (valor más frecuente)
df["category"] = df["category"].fillna(df["category"].mode()[0])

In [23]:
df

    rating      price  category    brand
0      1.0  10.500000       0.0     Sony
1      2.0  12.000000       1.0   Samsng
2      3.0   9.990000       2.0       LG
3      4.0   8.500000       0.0    Apple
4      5.0  10.433158       1.0     Sony
5      1.0  11.250000       2.0  Samsung
6      2.0  10.000000       0.0       LG
7      3.0  13.500000       1.0     Aple
8      4.0   9.000000       2.0     Sony
9      5.0  10.500000       0.0       LG
10     1.0  10.500000       0.0     Sony
11     2.0  12.000000       1.0   Samsng
12     3.0   9.990000       2.0       LG
13     4.0   8.500000       0.0    Apple
14     5.0   7.750000       1.0     Sony
15     1.0  11.250000       2.0  Samsung
16     2.0  10.000000       0.0       LG
17     3.0  13.500000       1.0     Aple
18     4.0   9.000000       2.0     Sony
19     5.0  10.500000       0.0       LG

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    20 non-null     float64
 1   price     20 non-null     float64
 2   category  20 non-null     float64
 3   brand     20 non-null     object
dtypes: float64(3), object(1)
memory usage: 772.0+ bytes

In [25]:
# Valores únicos antes de corregir errores de escritura
print(df["brand"].unique())

# Diccionario de corrección → unificamos nombres mal escritos
brand_map = {"Samsng": "Samsung", "Aple": "Apple"}
df["brand"] = df["brand"].replace(brand_map)

# Valores únicos después de la corrección
print(df["brand"].unique())

['Sony' 'Samsng' 'LG' 'Apple' 'Samsung' 'Aple']
['Sony' 'Samsung' 'LG' 'Apple']

In [26]:
# duplicated() marca con True las filas duplicadas
print(df.duplicated().sum())  # cuenta cuántas hay

9

In [27]:
# drop_duplicates() elimina las filas repetidas
df = df.drop_duplicates().reset_index(drop=True)
df

    rating      price  category    brand
0      1.0  10.500000       0.0     Sony
1      2.0  12.000000       1.0  Samsung
2      3.0   9.990000       2.0       LG
3      4.0   8.500000       0.0    Apple
4      5.0  10.433158       1.0     Sony
5      1.0  11.250000       2.0  Samsung
6      2.0  10.000000       0.0       LG
7      3.0  13.500000       1.0    Apple
8      4.0   9.000000       2.0     Sony
9      5.0  10.500000       0.0       LG
10     5.0   7.750000       1.0     Sony